# Generated by Django 5.2.3 on 2025-07-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectopm', '0003_remove_cliente_usuario_cliente_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
