# Generated by Django 5.2.3 on 2025-07-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectopm', '0004_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('anulado', 'Anulado')], default='pendiente', max_length=10),
        ),
    ]
